# The name of the project shown in the navigation bar (it links to the
# home page).
name: "Dynamic Statistical Comparisons"

# Link to the source repository (e.g., on Github).
repo: "https://github.com/stephenslab/dsc2"
site_url: "https://stephenslab.github.io/dsc-wiki"

# Footer added to the bottom of some webpages.
footer: 'Developed by <a href="http://home.uchicago.edu/gaow">Gao Wang</a>, <a href="https://pcarbo.github.io">Peter Carbonetto</a> and <a href="http://stephenslab.uchicago.edu">Matthew Stephens</a>.<br>&nbsp;&nbsp;&nbsp;This wiki is available under the <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution license</a> (read <a href="https://creativecommons.org/licenses/by/4.0/legalcode">full legal text</a>).'

# These directories contain .ipynb notebooks that will be rendered
# into webpages.
include_dir: ["tutorials", "installation", "examples", "manual"]

# Do not add links to the navigation bar for .ipynb notebooks in these
# directories.
# hide_navbar: ["playground"]

# Any .ipynb notebooks listed here will not be rendered into webpages
# (e.g., "analysis/temp.ipynb").
exclude_file: []

# Notebook used to generate home page.
homepage: "manual/Overview.ipynb"

# The name of the homepage link shown in the navigation bar.
homepage_label: "Home"

# Set this variable to enable auto-commit.
# release_message: "Build website with jnbinder."

add_commit_info: False
report_style: False
password_file: .passwd
