# The name of the project shown in the navigation bar (it links to the
# home page).
name: "Dynamic Statistical Comparisons"

# Link to the source repository (e.g., on Github).
repo: "http://github.com/stephenslab/dsc2"

# Footer added to the bottom of some webpages.
footer: '&copy 2016-2017 <a href="http://stephenslab.uchicago.edu">Stephens lab</a> at the University of Chicago.<br>&nbsp;&nbsp;&nbsp;This wiki is available under the <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution license</a> (read <a href="https://creativecommons.org/licenses/by/4.0/legalcode">full legal text</a>).'

# These directories contain .ipynb notebooks that will be rendered
# into webpages.
include_dir: ["manual", "tutorials", "examples", "development"]

# Do not add links to the navigation bar for .ipynb notebooks in these
# directories.
hide_navbar: ["development"]

# Any .ipynb notebooks listed here will not be rendered into webpages
# (e.g., "analysis/temp.ipynb").
exclude_file: []

# Notebook used to generate home page.
homepage: "manual/Overview.ipynb"

# The name of the homepage link shown in the navigation bar.
homepage_label: "Overview"

# Set this variable to enable auto-commit.
release_message: "Build website with jnbinder."

add_commit_info: False
